### ISSUE TITLE
Typo: replace read with write in lps28dfw_reference_mode_set

### ISSUE THREAD

**Issue by sfe-SparkFro** [STMicroelectronics/lps28dfw-pid#1]
This line needs to be replaced with `lps28dfw_write_reg`

https://github.com/STMicroelectronics/lps28dfw-pid/blob/9bc8409fd51befd50c3829c419deae6afab87a6e/lps28dfw_reg.c#L1121

I ran a quick test, and this change appears to work as expected. I can submit a pull request if you'd like, just let me know!

**Comment by sfe-SparkFro** [comment]
Same problem here:

https://github.com/STMicroelectronics/lps28dfw-pid/blob/9bc8409fd51befd50c3829c419deae6afab87a6e/lps28dfw_reg.c#L1048

Also related, looks to me as though the only way to enable the threshold interrupt conditions is by also enabling either the DRDY or one of the FIFO interrupt conditions. The INT_EN bit in CTRL_REG4 is only set when calling `lps28dfw_pin_int_route_set`, and is cleared if the DRDY and FIFO conditions are not active, so there's no way to enable only the threshold interrupts. This should probably be a separate issue, but figured I'd at least mention it.

**Comment by avisconti** [comment]
Closed via #3
